# Day 7a NumPy 
#1-Store Data Compactly
#2-Great for Big Numerical Operations
#3-Consume less memory

In [1]:
pip install numpy


### Defination of Array

In [ ]:
# Students of a class standing in the assembly is an ARRAY.
# Arym Troop in a prade are in the form of ARRAY.
# Students of class 1 to 5 in assemby each class array will be 1dimensional , and 5 Arrays = 5 dimensional
#Stake of CakeRusks in the bakery is an ARRAY

#2D ARRAY like sweets in the tray in bakery 

In [1]:
import numpy as np
a= np.array([5,5,5,5,5])
a

array([5, 5, 5, 5, 5])

In [2]:
# above is an 1D array.
type(a)

numpy.ndarray

In [17]:
#list of lists
import numpy as np
b= np.array([[1,2,2],[4,5,6],[7,8,9]])
b

array([[1, 2, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# above is a 2d array i.e period wise and group wise.b

In [8]:
# 1D is also called VECTOR . there is no difference in rows and coloumns because when they move column becom rows , rows coulumn
# 2d is also called MATRIX , assmebly of class 1 to 3 like (  1 1 1 
#                                                             2 2 2
#                                                             3 3 3  )

In [9]:
import numpy as np
a= np.array([5,5,5,5,5])
a

array([5, 5, 5, 5, 5])

In [10]:
type(a)

numpy.ndarray

In [11]:
len(a)

5

In [12]:
a[0:]

array([5, 5, 5, 5, 5])

In [18]:
#list of lists
import numpy as np
b= np.array([[1,2,2],[4,5,6],[7,8,9]])
b

array([[1, 2, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
type(b)

numpy.ndarray

In [20]:
len(b)

3

In [21]:
b[0]

array([1, 2, 2])

In [22]:
b[0:]

array([[1, 2, 2],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# 3D or higher
#the tensor is comonly used, tensor flow is a free library

In [ ]:
## Array Attributes
#Dimensions are called axis
#First axis is like | top to bottom
# Second Axis is like ----> left to right.

In [23]:
#list of lists
import numpy as np
b= np.array([[1,2,2],[4,5,6]])
b

array([[1, 2, 2],
       [4, 5, 6]])

In [ ]:
#above has , first axis length = 2 , Second axis length = 3

In [25]:
c=np.zeros(4)
c

array([0., 0., 0., 0.])

In [26]:
d=np.ones(6)
d

array([1., 1., 1., 1., 1., 1.])

In [30]:
e=np.empty(3)
e

array([ 8.31394666e-312,  0.00000000e+000, -6.47591605e-319])

In [31]:
#np linerly spaced arrays
f=np.linspace(0,10 ,num=5)
f

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [34]:
#with range of elements
g=np.arange(6)
g

array([0, 1, 2, 3, 4, 5])

In [35]:
# with specific range 
h= np.arange(2,20)
h

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [36]:
#continue 
i = np.arange (2,30, 3)   #3 is the differnce  
i

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29])

In [38]:
#specific data types 
j= np.ones(5, dtype=np.int8)            #5 is the number of output digits we want , int8 = we want only integers)
j

array([1, 1, 1, 1, 1], dtype=int8)

In [39]:
j= np.arange(5, dtype=np.int8)            #5 is the number of output digits we want , int8 = we want only integers)
j

array([0, 1, 2, 3, 4], dtype=int8)

In [40]:
k= np.arange(3, dtype=np.float64)            #3 is the number of output digits we want , float64 = we want only floats)
k

array([0., 1., 2.])

In [41]:
k= np.ones(3, dtype=np.float64)            #3 is the number of output digits we want , float64 = we want only floats)
k

array([1., 1., 1.])

In [42]:
#2D ARRAYS 
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [43]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [44]:
np.empty ((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
#3D ARRAY 
l=np.arange(24).reshape (2,3,4)
l

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
#( 2, 3, 4) is basically a 3D , How? Read Below
#2= 2 arrays ( 0 to 11) 1 array ,,,, ( 12 to 23 ) 2 array 
#3= | top to bottom there are 3 digits in both arrays 
#4= ---> left to right in both arrays are 4 digits 

# Day 7b

### Creating array using numpy

In [3]:
import numpy as np

In [4]:
a=np.array(["samosa" , "biryani" , "pakora"])
a

array(['samosa', 'biryani', 'pakora'], dtype='<U7')

In [5]:
b= np.array(["500", "400" , "100"])
b            

array(['500', '400', '100'], dtype='<U3')

In [5]:
type(a)

numpy.ndarray

In [6]:
len (a)

3

In [11]:
a[0]

'samosa'

In [11]:
np.mean(b)    # find the reason of error

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U3'), dtype('<U3')) -> None

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.ones(3)

array([1., 1., 1.])

In [14]:
np.empty(3)

array([1., 1., 1.])

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
#table
np.arange(0,55,5)           #last value is always exclusive

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [23]:
#linespace
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [31]:
#specify data type
np.arange(58, dtype= np.int64)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57], dtype=int64)

In [28]:
np.arange(7,dtype= np.float32)

array([0., 1., 2., 3., 4., 5., 6.], dtype=float32)

### Array Functions

In [33]:
a= np.array([10,6,7,9.9,3,5,67,9.67])
a

array([10.  ,  6.  ,  7.  ,  9.9 ,  3.  ,  5.  , 67.  ,  9.67])

In [35]:
a.sort()
a

array([ 3.  ,  5.  ,  6.  ,  7.  ,  9.67,  9.9 , 10.  , 67.  ])

In [ ]:
#you can practise all the functions by .tabbutton

In [36]:
b=([4,5,6,7,8,3,5])
b

[4, 5, 6, 7, 8, 3, 5]

In [37]:
np.concatenate((a,b))

array([ 3.  ,  5.  ,  6.  ,  7.  ,  9.67,  9.9 , 10.  , 67.  ,  4.  ,
        5.  ,  6.  ,  7.  ,  8.  ,  3.  ,  5.  ])

In [38]:
c= np.concatenate((a,b))
c.sort()
c

array([ 3.  ,  3.  ,  4.  ,  5.  ,  5.  ,  5.  ,  6.  ,  6.  ,  7.  ,
        7.  ,  8.  ,  9.67,  9.9 , 10.  , 67.  ])

### 2D arrays

In [39]:
a=np.array([[1,2,3] ,[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
b=np.array([[5,6,7] ,[8,9,10]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [42]:
c=np.concatenate((a,b))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [ ]:
# dimension should be same to concatenate 
# they can also be addup with diff dimensions but google it how 

In [44]:
#find dimension number
c.ndim

2

In [54]:
#sizecheck  (no.of elemnts)
c.size                

12

In [53]:
c.shape

(4, 3)

In [60]:
z=np.arange(9)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
y= z.reshape(3,3)
y

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Convert 1d to 2d

In [67]:
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a.ndim

1

In [68]:
a.shape

(9,)

In [70]:
b= a[np.newaxis , :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [71]:
b.shape

(1, 9)

In [73]:
b.ndim

2

In [74]:
#column wise
c= a[ : , np.newaxis ]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [80]:
#multiply
a * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [76]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [82]:
a.mean()

5.0

In [83]:
a.sum()

45

In [ ]:
### go to google , numpy , begineers guide and see all the manuals and functions